#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

outfile=jscribble/VersionName.java

if [[ -d .git ]]
then
	version=$(git describe --always --tags)
else
	# TODO add better defaults here
	version=NA
	revno=NA
fi

echo "package jscribble;" > "$outfile"
echo "/**" >> "$outfile"
echo " * Version name dummy." >> "$outfile"
echo " */" >> "$outfile"
echo "public class VersionName {" >> $outfile
echo "	/**" >> "$outfile"
echo "	 * Current version number of the VCS." >> "$outfile"
echo "	 */" >> "$outfile"
echo "	public static final String version = \"$version\";" >> $outfile
echo "}" >> $outfile
echo >> $outfile

