#!/bin/bash
# Copyright © 2011 Martin Ueding <dev@martin-ueding.de>

version=$1

echo "package jscribble;"
echo "/**"
echo " * Version name dummy."
echo " */"
echo "public class VersionName {"
echo "	/**"
echo "	 * Current version number of the VCS."
echo "	 */"
echo "	public static final String version = \"$version\";"
echo "}"
echo
