.\" Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>
.TH jscribble 1 "2011-04-05" "0.1" "Infinite Notebook"
.SH NAME
jscribble \- Infinite Graphical Notebook
.SH SYNOPSIS
\fBjscribble\fP
.SH DESCRIPTION
Usual graphics programs cannot be easily used for note taking since you cannot
create many pages. Handling individual pictures is not very handy. jscribble
allows you to handle a collection of pages in a notebook and flip though them
easily.
.SH AUTOR
Martin Ueding <dev@martin-ueding.de>
.SH COPYRIGHT
Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>
