#!/usr/bin/php

# This file is part of jscribble.
#
# jscribble is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later
# version.
#
# jscribble is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# jscribble.  If not, see <http://www.gnu.org/licenses/>.

_jscribble() {
	local cur
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}

	case "$cur" in
		*)
			COMPREPLY=( $(compgen -W '-v' -- $cur) \
				$(compgen -W '
<?php
$file = file_get_contents('config/config.js');
$config = json_decode($file, true);

foreach ($config as $item) {
	echo ' --'.$item['key'];
}

?>
				' -- $cur)
			)
			;;
	esac

	if (( COMP_CWORD > 0 ))
	then
		prev=${COMP_WORDS[((COMP_CWORD-1))]}

		case "$prev" in
			<?php
			foreach ($config as $item) {
				if ($item['type'] == 'Boolean') {
					$keys[] = '--'.$item['key'];
				}
			}
			echo implode('|', $keys);
			?>)
				COMPREPLY=( $(compgen -W 'true false' -- $cur) )
				;;
		esac
	fi

	return 0
}

complete -F _jscribble jscribble

# vim: ft=sh
