#!/usr/bin/php
_jscribble() {
	local cur
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}

	case "$cur" in
		*)
			COMPREPLY=( $(compgen -W '-v' -- $cur) \
				$(compgen -W '
<?php
$file = file_get_contents('config/config.js');
$config = json_decode($file, true);

foreach ($config as $item) {
	echo ' --'.$item['key'];
}

?>
				' -- $cur)
			)
			;;
	esac

	return 0
}

complete -F _jscribble jscribble

# vim: ft=sh
