// Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

package jscribble;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.swing.JOptionPane;

/**
 * The main program.
 *
 * @author Martin Ueding <dev@martin-ueding.de>
 */
public class NoteBookProgram {
	/**
	 * Suffix that is appended to every NoteBook configuration file.
	 */
	public static String configFileSuffix = ".jscribble-notebook";


	/**
	 * Generates a "generated by <program name> <version>" string.
	 *
	 * @return version string
	 */
	public static String generatedComment() {
		return "generated by jscribble " + VersionName.version;
	}

	/**
	 * Handles some error message centrally, right now it just displays a dialog box with the error message.
	 *
	 * @param string error message
	 */
	public static void handleError(String string) {
		JOptionPane.showMessageDialog(null, string);
	}

	static BufferedOutputStream outstream;

	public static void log(String string, String format) {
		String output = string + ":\t" + format;
		System.out.println(output);

		if (outstream != null) {
			try {
				outstream.write((output + "\n").getBytes());
			}
			catch (IOException e) {
				System.out.println(output);
				e.printStackTrace();
			}
		}
	}


	/**
	 * Displays the NotebookSelectionWindow.
	 *
	 * @param args ignored CLI arguments
	 */
	public static void main(String[] args) {
		try {
			outstream = new BufferedOutputStream(new FileOutputStream(new File("/tmp/jscribble.log")));
		}
		catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		log(NoteBookProgram.class.getClass().getName(), "Starting up.");

		if (args.length > 0 && args[0].equals("--version")) {
			System.out.println("Version: " + VersionName.version);
		}

		NotebookSelectionWindow nsw = new NotebookSelectionWindow();
		nsw.showDialog();

		log(NoteBookProgram.class.getClass().getName(), "Entering interactive mode.");
	}

	private static File dotDir = new File(System.getProperty("user.home") + File.separator + ".jscribble");

	public static File getDotDir() {
		return dotDir;
	}

}